# S03 T04


## Level 1

### - Exercise 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.


In [1]:
import numpy as np
from scipy import stats


n = int(input("Enter the size of list : "))
print("\n")
arr = list(map(float, input("Enter the list numbers separated by space ").strip().split()))
matrix = np.array(arr)

if matrix.ndim == 1:
    print("\n")
    print("User List: ", matrix)
    print("\n")
    print(stats.describe(matrix))
else:
    print ("Error")

Enter the size of list : 3


Enter the list numbers separated by space 1.1 2 3.3


User List:  [1.1 2.  3.3]


DescribeResult(nobs=3, minmax=(1.1, 3.3), mean=2.1333333333333333, variance=1.223333333333333, skewness=0.21824567180387883, kurtosis=-1.4999999999999998)


### -Exercise 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [6]:
import numpy as np
from numpy import random

x = random.randint(10)
m = random.randint(100, size=(x, x))

print(m)

[[83 99  3]
 [26 92 45]
 [26 78 29]]


### - Exercise 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [82]:
def myadd1(mat1):
    newarr1 = np.sum([mat1], axis=1)        
    newarr2 = np.sum([mat1], axis=2)
    return newarr1, newarr2

print(myadd1(m))
    



(array([[135, 269,  77]]), array([[185, 163, 133]]))


### - Exercise 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [119]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

r = np.corrcoef(m,m)
print(r)

[[1.         0.38608545 0.58783005 1.         0.38608545 0.58783005]
 [0.38608545 1.         0.97321086 0.38608545 1.         0.97321086]
 [0.58783005 0.97321086 1.         0.58783005 0.97321086 1.        ]
 [1.         0.38608545 0.58783005 1.         0.38608545 0.58783005]
 [0.38608545 1.         0.97321086 0.38608545 1.         0.97321086]
 [0.58783005 0.97321086 1.         0.58783005 0.97321086 1.        ]]


In [117]:
import matplotlib.pyplot as plt
import seaborn as sns


x = np.arange(10, 20)
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
re = np.corrcoef(x, y)
print(re)



[[1.         0.75864029]
 [0.75864029 1.        ]]
