# S03 T04


## Level 1

### - Exercise 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.


In [1]:
import numpy as np
from scipy import stats


n = int(input("Enter the size of list : "))
print("\n")
arr = list(map(float, input("Enter the list numbers separated by space ").strip().split()))
matrix = np.array(arr)

if matrix.ndim == 1:
    print("\n")
    print("User List: ", matrix)
    print("\n")
    print(stats.describe(matrix))
else:
    print ("Error")

Enter the size of list : 3


Enter the list numbers separated by space 1.1 2 3.3


User List:  [1.1 2.  3.3]


DescribeResult(nobs=3, minmax=(1.1, 3.3), mean=2.1333333333333333, variance=1.223333333333333, skewness=0.21824567180387883, kurtosis=-1.4999999999999998)


### -Exercise 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [6]:
import numpy as np
from numpy import random

x = random.randint(10)
m = random.randint(100, size=(x, x))

print(m)

[[83 99  3]
 [26 92 45]
 [26 78 29]]


### - Exercise 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [20]:
def myadd1(mat1):
    newarr1 = np.sum([mat1], axis=1)        
    newarr2 = np.sum([mat1], axis=2)
    return newarr1, newarr2
print (m)
print(myadd1(m))
    



[[21 49 53]
 [12 59 33]
 [15 74 99]]
(array([[ 48, 182, 185]]), array([[123, 104, 188]]))


### - Exercise 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [23]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

r = np.corrcoef(m, m)
print (m)
print(r)

[[21 49 53]
 [12 59 33]
 [15 74 99]]
[[1.         0.76490475 0.98401007 1.         0.76490475 0.98401007]
 [0.76490475 1.         0.63794378 0.76490475 1.         0.63794378]
 [0.98401007 0.63794378 1.         0.98401007 0.63794378 1.        ]
 [1.         0.76490475 0.98401007 1.         0.76490475 0.98401007]
 [0.76490475 1.         0.63794378 0.76490475 1.         0.63794378]
 [0.98401007 0.63794378 1.         0.98401007 0.63794378 1.        ]]


In [29]:
import matplotlib.pyplot as plt
import seaborn as sns


x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 4, 5, 3, 2])
re = np.corrcoef(x, y)
re1 = re[0,1]

print ("Matriz de correlaciones:")
print(re)
print(" ")
print("Coeficiente de correlación:")
print(re1)


Matriz de correlaciones:
[[ 1.  -0.9]
 [-0.9  1. ]]
 
Coeficiente de correlación:
-0.8999999999999998


In [21]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 4, 5, 3, 2])

r = (np.cov(x,y))/(np.std(x,ddof=1)*np.std(y,ddof=1))
r1 = (np.cov(x,y)[0,1])/(np.std(x,ddof=1)*np.std(y,ddof=1))
#El elemento [0, 1] es el valor relevante para el cálculo
#Es necesario usar ddof=1 en np.std porque retorna a estimativa imparcial

print ("Matriz de correlaciones:")
print (r)
print(" ")
print("Coeficiente de correlación:")
print (r1)

Matriz de correlaciones:
[[ 1.  -0.9]
 [-0.9  1. ]]
 
Coeficiente de correlación:
-0.8999999999999998
